groups:
- name: latency_alerts
  rules:
  - alert: HighRequestLatency
    expr: histogram_quantile(0.95, sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{job="shuup"}[$__rate_interval])) by (le)) > 0.2
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High request latency detected"
      description: "The 95th percentile request latency is above 200ms for the last 5 minutes."
